---
- name: Create ELK directory
  ansible.builtin.file:
    path: "{{ elk_dir }}"
    state: directory
    mode: '0755'
- name: Create Elasticsearch data directory
  ansible.builtin.file:
    path: "{{ elasticsearch_data_dir }}"
    state: directory
    owner: 1000
    group: 1000
    mode: '0775'
- name: Create Logstash pipeline directory
  ansible.builtin.file:
    path: "{{ logstash_pipeline_dir }}"
    state: directory
    mode: '0755'
- name: Template logstash.conf
  ansible.builtin.template:
    src: logstash.conf.j2
    dest: "{{ logstash_pipeline_dir }}/logstash.conf"
    mode: '0644'
  notify: rebuild_elk
- name: Template docker-compose.yml
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ elk_dir }}/docker-compose.yml"
    mode: '0644'
  notify: rebuild_elk
- name: Pull ELK images
  community.docker.docker_image:
    name: "{{ item }}"
    source: pull
  loop:
    - "{{ elasticsearch_image }}"
    - "{{ logstash_image }}"
    - "{{ kibana_image }}"
- name: Start ELK with Docker Compose
  community.docker.docker_compose_v2:
    project_src: "{{ elk_dir }}"
    state: present
